version: '3'

services:
  proxy:
    build:
      context: .
    user: http-proxy
    command: bash -c "cd build && ./http-proxy"
    ports:
      - "8080:8080"
    volumes:
      - /var/log:/var/log
      